#!/bin/bash
# Quick reference for PyPI publication

echo "=== PyPI Publication Quick Reference ==="
echo ""
echo "📋 Pre-Flight Checklist:"
echo "  □ Version bumped in pyproject.toml"
echo "  □ All tests passing (pytest tests/ -v)"
echo "  □ Git committed and pushed"
echo "  □ PyPI token configured (poetry config pypi-token.pypi TOKEN)"
echo ""
echo "🔨 Build & Test:"
echo "  ./scripts/build.sh              # Build packages"
echo "  ./scripts/test-install.sh       # Test installation locally"
echo ""
echo "🚀 Publish:"
echo "  ./scripts/publish.sh            # Interactive publish wizard"
echo ""
echo "  OR manually:"
echo "  poetry publish -r testpypi      # Test on TestPyPI first"
echo "  poetry publish                  # Production PyPI"
echo ""
echo "📦 Verify:"
echo "  pip install mcp-server-jupyter  # Test from PyPI"
echo "  mcp-jupyter --help              # Verify CLI works"
echo ""
echo "📚 Full documentation: PYPI.md"
